### ISSUE TITLE
Please do not bundle org-insert-dbblock.el in two repositories

### ISSUE THREAD

**Issue by tarsius** [tbanel/orgtbljoin#1]
If at all possible, then a repository used to maintain an Emacs package should not bundle any libraries that are also being tracked in other repositories.

I recommend that you never bundle any libraries.  If that is not possible, then I recommend that you put those libraries in a separate directory and alongside a file named `.nosearch`. The existence of this file instructs some tools (such as `normal-top-level-add-subdirs-to-load-path`, my [`borg`](https://emacsair.me/2016/05/17/assimilate-emacs-packages-as-git-submodules/) package manager, and the tools I use to maintain the Emacsmirror) to ignore the containing directory.

Thanks for considering this!

<sub>I have written similar messages many many times so I now [use a template](https://help.github.com/en/github/writing-on-github/working-with-saved-replies). I try to adjust it to match each individual case but it might still not apply 100% in all cases.</sub>

In this particular case, since you are the author of all of the involved libraries, I would recommend creating a third repository for `org-insert-dblock.el`.

**Comment by tarsius** [comment]
Off-topic: I noticed you are struggling to decide where to place the `-*- coding:utf-8;-*-`. I am afraid there is only one correct way, you are not using it and it is the most ugly variant:

```
;;; org-insert-dblock.el --- Wizzard to insert a dynamic block  -*- coding:utf-8;-*-
```

* The summary *must* appear on the very first line or the tools that look for it won't find it.
* The local variable *must* be set on the very first line or they won't be used.
* Therefore both of these things have to be done on the same line.

**Comment by tbanel** [comment]
Jonas,

You are perfectly right. I use the same file, namely `org-insert-dblock.el`, in two distinct packages. It was intended to be a temporary situation, until Emacs Org Mode integrates those features. This has partially happened (`C-c C-x x`) (`M-x org-dynamic-block-insert-dblock`). So I may decide that `org-insert-dblock.el` will just vanish. Or maybe I may merge my two packages so as to have just one instance of `org-insert-dblock.el`.

Anyway, I need some peace of mind to do the required change. Which I don't have right now, because I am in the midst of an economic turmoil. I face the very real possibility to be fired in a short time, and hard times looking for a new job.

Be assured that I will consider your suggestion as soon as I can.

Thanks for your interest
Thierry

**Comment by tbanel** [comment]
Tarsius,
I just applied your recommendation about UTF8
Thanks for reporting!

**Comment by tarsius** [comment]
I wish you all test best!

Look after yourself and don't feel pressured to deal with this issue before you have the peace of mind to deal it. It's just a little nuisance that can wait.

**Comment by tarsius** [comment]
Just a friendly ping. Feel free to ignore if you can't deal with this still, though a little heads up would be appreciated. Cheers!

**Comment by tbanel** [comment]
Hi Jonas
I don't forget your wise recommendation. I will come back to it when I will recover peace of mind, hopefully soon.
Cheers
